### ISSUE TITLE
pico_contributors in pico-cms 0.9 - Draws a blank, HTTP 500 page - php5-intl required for Class 'Locale'

### ISSUE THREAD

**Issue by kriskropd** [yomli/pico-plugins#1]
I cloned the github repo, moved 'pico_contributors' subdirectory to plugins/ with all my other, working pico-cms plugins. When I try to visit the site.com/contribute page, I simply recieve a blank page with HTTP error 500.

`[error] 2632#0: *287 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: pico_contributor in /usr/share/nginx/site/plugins/pico_contributors/pico_contributors.php on line 254`
`PHP message: PHP Fatal error:  Class 'Locale' not found in /usr/share/nginx/site/plugins/pico_contributors/lib/helper_strings.php on line 53" while reading response header from upstream, client: client-ip, server: _, request: "GET /contribute HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "blog.site.com"`

Nginx & PHP-FPM

**Comment by kriskropd** [comment]
Okay, I resolved the Class 'Locale' issue by installing package `php5-intl` on this Debian server I'm working on. Someone else may have this issue later.

The pico_contributor undefined index is still an issue, but it's not page-breaking like the Locale Class was. It does, however, spam the logfile if php.ini isn't configured to ignore repeating error messages.

**Comment by yomli** [comment]
Thanks for your input.
The default value of php.ini [ignore notices](https://secure.php.net/manual/en/errorfunc.configuration.php#ini.error-reporting). Like you said, it's not page-breaking, so if you worry about the logfile, you can add this line to `contributors_config.php` until I commit :

``` PHP
error_reporting(E_ALL & ~E_NOTICE);
```

**Comment by kriskropd** [comment]
Okay, I'll add that error reporting locally and close this issue then.
