### ISSUE TITLE
Mistaken Assets File Path

### ISSUE THREAD

**Issue by kriskropd** [yomli/pico-plugins#3]
Despite my config.php indicating `$config['content_dir'] = 'content/';` When I click on the Assets button on the contribute page, I receive

> Error (check file permissions) - create directory failed at: /usr/share/nginx/site/content-sample/images/admin

Also, when saving new pages, the red "Saving..." text with red background appears in top-right corner and remains indefinitely. Likely related.

Is it not pulling $config['content_dir'] from the config.php? Do I need to change it for pico_contribute elsewhere?

**Comment by yomli** [comment]
Pico Contributors uses the const `CONTENT_DIR` which come from Pico (see your `index.php`). There is no mention of _content-sample_ in Pico Contributors, so it's likely [an issue with your Pico](https://github.com/picocms/Pico/issues/243).

**Comment by kriskropd** [comment]
I see. I'm still new to Pico CMS and didn't see `CONTENT_DIR` before. That would be my mistake then and I'll close this issue.
